apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-version-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: version-exporter
    galleon: {{ .Values.galleonName }}
